version: '3'
services:
  client:
    container_name: beautifood-lite-client
    restart: unless-stopped
    expose:
      - 80
    image: registry-intl.ap-southeast-1.aliyuncs.com/swmeng/beautifood-lite-client:${BUILD_NUMBER}
    labels:
      caddy: app.lite.beautifood.io
      caddy.reverse_proxy: "{{upstreams 80}}"
networks:
  default:
    external:
      name: caddy
